# Generated by Django 5.2.17 on 2026-09-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.TextField()),
                ('pos', models.IntegerField()),
                ('uid', models.TextField(null=True)),
                ('ref', models.TextField()),
                ('alt', models.TextField(null=True)),
                ('qual', models.FloatField(null=True)),
                ('filter', models.TextField(null=True)),
                ('info', models.TextField(null=True)),
                ('gt', models.TextField(null=True)),
                ('phase_set', models.IntegerField(null=True)),
                ('depth', models.IntegerField(null=True)),
                ('allel_depth_all', models.TextField(null=True)),
                ('allel_depth_nofilt', models.TextField(null=True)),
                ('genotype_quality', models.IntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['chrom', 'pos'], name='find_genoty_chrom_3307d8_idx')],
            },
        ),
    ]
