# Generated by Django 5.2.17 on 2026-09-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.TextField()),
                ('pos', models.IntegerField()),
                ('uid', models.TextField()),
                ('ref', models.TextField()),
                ('alt', models.TextField()),
                ('qual', models.FloatField()),
                ('filter_status', models.TextField()),
                ('info', models.TextField()),
                ('genotype_format', models.TextField()),
                ('genotype_id', models.TextField()),
            ],
        ),
    ]
